name: On Push flow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-16.04
    steps:
      - name: echo a string test
        run: echo "Hello"
      - name: Multipline script test
        run: |
          node -v
          npm -v
          ls -l
          pwd
      - name: Python cmd test
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-cmd:
    runs-on: windows-latest
    steps:
      - name: Test powetshell
        shell: powershell
        run: Get-Location
      - name: Test bash
        shell: bash
        run: pwd
